# Generated by Django 4.2.24 on 2025-09-15 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseProduct",
            fields=[
                (
                    "random_key",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("persian_name", models.CharField(max_length=255)),
                ("english_name", models.CharField(max_length=255)),
                ("extra_features", models.JSONField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BaseView",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("base_product_rk", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("parent_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Search",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uid", models.CharField(max_length=100)),
                ("query", models.TextField()),
                ("page", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.CharField(max_length=100)),
                ("result_base_product_rks", models.JSONField()),
                ("category_id", models.IntegerField(default=0)),
                ("category_brand_boosts", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("city_id", models.IntegerField()),
                ("score", models.FloatField()),
                ("has_warranty", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "random_key",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("shop_id", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "base_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.baseproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalClick",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("shop_id", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "base_view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.baseview"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="baseview",
            name="search",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.search"
            ),
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.brand"
            ),
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.category"
            ),
        ),
    ]
